### PR TITLE
updated json & fixed photo bug

### PR DESCRIPTION
**Pull request by sward42**
I updated the json file to include new data and fixed a bug with Jennifer and Dustin's photos

### CODE REVIEW

**Comment by debragordon** [comment]
@sward42 put the http:// before all the www. ... websites ... see how i formatted all the others

It will help when loading and staying consistent

**Comment by debragordon** [comment]
I see it with Blair, Josh, Owen, Lee

**Comment by debragordon** [comment]
@sward42 let me know when you push an updated json up and I will review and give a thumbs up for a merge so you will have the most up to date code

**Comment by sward42** [comment]
should be good

**Comment by debragordon** [comment]
looks good, thanks for streamlining ...

good to merge

**Pull request merged**
