### PR TITLE
added scrolling effect

### PR DESCRIPTION
**Pull request by justinal64**
Added scroll effect to page and added a home button to the nav bar, so the user could get back to the very top of the page.

### CODE REVIEW

**Comment by debragordon** [comment]
@justinal64 the E4 at the top (in the nav) is the "home" button

Can you take that out and re-push?

**Comment by debragordon** [comment]
when I say take "that out" i mean the home button you added and leave the E4 as the home button

**Comment by justinal64** [comment]
Did you mean to close my PR?

**Comment by debragordon** [comment]
@justinal64 yes ...

**Pull request closed without merging**
